import './globals.css';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

// import { TRPCReactProvider } from '@/trpc/react'
// import { headers } from 'next/headers'

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    // <TRPCReactProvider headers={headers()}>
    <html lang='en'>
      <body className={inter.className}>{children}</body>
    </html>
    // </TRPCReactProvider>
  );
}
